name: Test suite

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the `main` branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  swift-test:
    strategy:
      matrix:
        include:
          - os: macos-12
            swift_version: 5.6
            xcode: /Applications/Xcode_13.4.app/Contents/Developer
          - os: macos-11
            swift_version: 5.5
            xcode: /Applications/Xcode_13.2.1.app/Contents/Developer
          - os: ubuntu-20.04
            swift_version: 5.6
          - os: ubuntu-18.04
            swift_version: 5.6
    name: Build on ${{ matrix.os }} with Swift ${{ matrix.swift_version }}
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Run `swift test`
        run: swift test
